### ISSUE TITLE
Supporting 3D array

### ISSUE THREAD

**Issue by jakeoung** [cdsousa/CuTextures.jl#2]
Thanks for the amazing work. I may be wrong, but is it right that this package doesn't support 3D array yet?

For example, I have a 3D voxel image and I want to interpolate at a specific position.

**Comment by cdsousa** [comment]
It does, check some examples in here https://github.com/cdsousa/CuTextures.jl/blob/master/test/runtests.jl.
Anyway, be aware that this is has been just a proof of concept and there are lots of improvements needed, that's why I have not registered the package. And I haven't looked into it for some time.
